### ISSUE TITLE
Do you mind upgrading dependencies?

### ISSUE THREAD

**Issue by akefirad** [arteam/simple-json-rpc#11]
Do you mind upgrading dependencies, as well as refactoring to remove dependency on Guava, Intellij Annotations, etc? (I can work on the a PR, if needed.)

**Comment by arteam** [comment]
Hey @akefirad, I just updated the dependencies and bumped the baseline for the project to JDK8.
It's been released to Maven Central as 1.0. Let me know if it works for you!

**Comment by akefirad** [comment]
@arteam thanks for taking care of it. Will update you.
