### ISSUE TITLE
JsonRpcError's code is restricted to server error codes only

### ISSUE THREAD

**Issue by mnasyrov** [arteam/simple-json-rpc#2]
Hi Artem!

I'm using `@JsonRpcError` annotation for returning an application error back to a client, for example:
```java
@JsonRpcError(code = 401, message = "Not authenticated")
private static class AuthError extends RuntimeException {
}
```

When `JsonRpcServer` handles the error it logs a following message:
```
2017-12-20 17:38:31:070 +0700 [WebSocketWorker-20] WARN com.github.arteam.simplejsonrpc.server.JsonRpcServer - Error code=401 not in a range [-32099;-32000]
```

It seems there is no a need for the warning about exceeding the range of server errors, because [JSON-RPC 2.0 spec](http://www.jsonrpc.org/specification) reservers [-32768; -32000] range for transport related errors:
* protocol error codes: -32700, -32600, -32601, -32602, -32603;
* error codes which are related to an implementation of JSON-RPC server: [-32099, -32000];
* the rest error codes of the main range are reserved for future use by JSON-RPC.

Please correct me if I'm wrong but all another error codes are allowed for using by an application.

What do you think about this case?

**Comment by arteam** [comment]
You're right. It was an oversight from my side. I will fix it in the next release.
